spring:
  ai:
    mcp:
      server:
        name: redis-statics-spring-mcp
        version: 1.0.0
        type: SYNC
        tools:
          base-package: dev.study.springmcpmodel.tool

  data:
    redis:
      host: localhost
      port: 6379
  main:
    web-application-type: servlet